app/controllers/appointments_controller.rb
app/controllers/journal_entries_controller.rb
app/controllers/meals_controller.rb
app/controllers/medicines_controller.rb
app/controllers/pets_controller.rb
test/controllers/appointments_controller_test.rb
test/controllers/journal_entries_controller_test.rb
test/controllers/meals_controller_test.rb
test/controllers/medicines_controller_test.rb
test/controllers/pets_controller_test.rb

(empty) controllers for: 
pets
meals
medicines
journal_entries
appointments

generated 5 controllers

---

app/controllers/application_controller.rb
app/controllers/appointments_controller.rb
app/controllers/journal_entries_controller.rb
app/controllers/meals_controller.rb
app/controllers/medicines_controller.rb
app/controllers/pets_controller.rb
test/controllers/appointments_controller_test.rb
test/controllers/journal_entries_controller_test.rb
test/controllers/meals_controller_test.rb
test/controllers/medicines_controller_test.rb
test/controllers/pets_controller_test.rb

sorry forgot to add this to my pundit installation pull

Pundit setup

---

Gemfile.lock
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_colors.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/buttons/_backbtn.html.erb
app/views/shared/buttons/_lgplusbtn.html.erb
app/views/shared/buttons/_logoutbtn.html.erb
app/views/shared/buttons/_pawbtn.html.erb
app/views/shared/buttons/_plutbtn.html.erb
app/views/shared/buttons/_selectmenumid.html.erb
app/views/shared/buttons/_selectmenusm.html.erb
app/views/shared/buttons/_signinbtn.html.erb
app/views/shared/buttons/_signoutbtn.html.erb
app/views/shared/buttons/_userprofilesbtn.html.erb

and attempted select menu, to add with simple form later
to view all buttons visit the home page.

created components for all buttons 

---

Gemfile
Gemfile.lock
app/controllers/journal_entries_controller.rb
db/seeds.rb

Journal seeds

---

db/seeds.rb

added pets to journal

---

app/assets/stylesheets/components/_family_pet_card.scss
app/views/pets/index.html.erb
db/seeds.rb

Created functionality for index and updated seeds

Family dashboard pets index

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/views/pets/profile.html.erb
config/routes.rb

pet profile

---

app/views/journal_entries/_form.html.erb
app/views/journal_entries/index.html.erb
app/views/pets/profile.html.erb
app/views/pets/show.html.erb

the issue was that we have the journal allowing many photos, so just having photos.key means that youre trying to convert an array into an img, so i changed it to first. 
i dont think we want more than one imgs per journal but prolly no need to change the validations

you can now view journal photos

---

app/assets/stylesheets/components/_family_pet_card.scss
app/views/pets/profile.html.erb
app/views/pets/show.html.erb

fixed the link so we can see pet profile by clicking on picture in individual pet dashboard

connected pet dashboard and pet profile

---

app/assets/stylesheets/components/_family_pet_card.scss
app/controllers/journal_entries_controller.rb
app/views/pets/profile.html.erb
app/views/pets/show.html.erb

Journal entries are now sorted newest first 
(sorry all my pulls seem to have conflicts-- i dont even know what they are cause theyre not showing)

Journal sort

---

app/assets/stylesheets/components/_family_pet_card.scss
app/controllers/journal_entries_controller.rb
app/javascript/packs/navbar.js
app/views/journal_entries/new.html.erb
app/views/pets/profile.html.erb
app/views/pets/show.html.erb
config/application.rb

Time date for active storage has been changed to JST (this was updated for journal entries)

Journal time date

---

app/assets/stylesheets/pages/_profile.scss
app/views/pets/profile.html.erb

sorry i had two width classes for some reason lol
i also centered the text!

fixed avatar stretch on profile pg

---

app/assets/stylesheets/components/_buttons.scss
app/views/pets/profile.html.erb

fixed back btn and the back btn color changed to black for now

Back btn fix

---

app/assets/stylesheets/components/_navbar.scss
app/javascript/packs/navbar.js

navbar no longer needs to be clicked twice

fixed the navbar double click error

---

app/views/pets/profile.html.erb

you can now view pet journal imgs in profile

---

db/seeds.rb

this shit assigns medication at random to pets............... Not sure if this is the best method but it works so FUGIT

medicine seeds!

---

app/views/journal_entries/index.html.erb
app/views/pets/profile.html.erb

you can now view multiple pictures from one journal

Journal entry multipics

---

app/controllers/appointments_controller.rb
app/policies/appointment_policy.rb
app/views/appointments/index.html.erb
app/views/pets/show.html.erb
config/routes.rb

pushing now so jessica can add her stuff to the controller

created appointment routes, controller and policy

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_appointments.scss
app/views/appointments/index.html.erb

removed picture, added see more, added nothing here yet, removed text decoration for ALL PLUTO LINKS

Beautified Appo Index See description

---

app/assets/stylesheets/pages/_medicine_index.scss
app/views/medicines/index.erb

at least it looks somewhat orderly now

These are copied cards from the meals

---

app/views/medicines/_form.html.erb
app/views/medicines/new.html.erb

Its not exactly like the figma because I took some creative liberties but feel free to change. Here is what it looks like:

made the form like the figma

---

app/assets/stylesheets/pages/_pets_show.scss
app/assets/stylesheets/pages/_profile.scss
app/views/pets/profile.html.erb
app/views/pets/show.html.erb

Add sex to pet in profile

---

Gemfile
Gemfile.lock
app/controllers/line_controller.rb
app/services/line_bot.rb
config/environment.rb
config/environments/development.rb
config/routes.rb
db/schema.rb
test/controllers/line_controller_test.rb

basic line bot. Need to get this on heroku asap.

Implemented Line bot

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_medicine_index.scss
app/assets/stylesheets/pages/_medicines_show.scss
app/controllers/appointments_controller.rb
app/policies/appointment_policy.rb
app/views/appointments/index.html.erb
app/views/journal_entries/new.html.erb
app/views/medicines/_form.html.erb
app/views/medicines/index.html.erb
app/views/medicines/show.html.erb
config/routes.rb

medicine show cleanup, accidentally made this branch inside index branch, so this includes index and show cleanup
p

Medicine show view cleanup

---

app/assets/stylesheets/pages/_appointments_show.scss
app/views/appointments/index.html.erb
app/views/appointments/new.html.erb
app/views/appointments/show.html.erb
app/views/journal_entries/index.html.erb
app/views/meals/index.html.erb
app/views/meals/new.html.erb
app/views/pets/index.html.erb
app/views/pets/show.html.erb

also just changed the placement of the location icon

made sure everything was capitalized (EXCEPTION: Journal entries content)

---

app/views/pets/index.html.erb

got rid of weird line when a pet doesnt have an age

refactored pets age card

---

app/controllers/ownerships_controller.rb
app/controllers/pets_controller.rb
app/views/pets/index.html.erb
config/routes.rb
db/migrate/20220827074222_add_main_to_ownerships.rb
db/schema.rb
db/seeds.rb

- added migration file to add main to ownerships. pets that aren't main won't be added to other users
- adjusted order in index

Second user pet bug

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_ownership_form.scss
app/assets/stylesheets/pages/_ownership_new.scss
app/views/ownerships/_form.html.erb
app/views/ownerships/new.html.erb

This was the best thing I could come up with with advice form TA's... very open to any changes for what the results look like

Add ownership stylizing

---

app/views/ownerships/new.html.erb
db/schema.rb

you cannot add yourself to your family
you cannot add someone without an account to your family
you cannot add someone already in your family, to your family

adding user to family alerts

---

app/assets/stylesheets/pages/_family_pet_index.scss
app/views/pets/index.html.erb

aligned and added padding to sex icon

---

app/javascript/packs/likes.js
app/views/journal_entries/_like_button.html.erb
app/views/journal_entries/index.html.erb
app/views/meals/index.html.erb
app/views/medicines/index.html.erb

it now works
(also readded the journal Entry does not exist yet, so add a new one title that mysteriously vanished)

fixed like btn

---

app/assets/stylesheets/pages/_pets_show.scss
app/views/pets/show.html.erb

fixed overlapped header and aligned the buttons

---

db/schema.rb
db/seeds.rb

fixed the seeds for journals

---

app/views/appointments/show.html.erb
app/views/journal_entries/index.html.erb
app/views/meals/index.html.erb
app/views/medicines/show.html.erb
app/views/pets/profile.html.erb

When you click on an image in the individual pet profile page it opens it up as a link
https://user-images.githubusercontent.com/74501096/187637698-31adcc96-e70d-490f-95e6-5cd63dc12422.mov

click to enlarge image

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_whitebg.scss
app/views/appointments/show.html.erb
app/views/devise/sessions/new.html.erb
app/views/journal_entries/new.html.erb
app/views/meals/_form.html.erb
app/views/meals/new.html.erb
app/views/medicines/_form.html.erb
app/views/medicines/new.html.erb
app/views/ownerships/new.html.erb
app/views/pets/new.html.erb

Also added back btn to add pet form

added white bg behind text

---

app/controllers/meals_controller.rb
app/controllers/medicines_controller.rb
app/models/medicine.rb
app/models/pet.rb
app/views/appointments/_form.html.erb
app/views/meals/_form.html.erb
app/views/medicines/_form.html.erb
app/views/pets/show.html.erb

fix the notifications backend

---

app/controllers/pages_controller.rb
app/views/pages/home.html.erb

home page now is the blue page

edited extra page
